# Generated by Django 5.2.6 on 2025-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunciopractica',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='anunciopractica',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='anunciopractica',
            name='duracion_meses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='anunciopractica',
            name='jornada',
            field=models.CharField(choices=[('tiempo completo', 'Tiempo Completo'), ('medio tiempo', 'Medio Tiempo'), ('flexible', 'Flexible')], default='tiempo completo', max_length=50),
        ),
        migrations.AddField(
            model_name='anunciopractica',
            name='requisitos',
            field=models.TextField(default='No se especifican requisitos.'),
        ),
        migrations.AddField(
            model_name='anunciopractica',
            name='tipo_practica',
            field=models.CharField(choices=[('profesional', 'Profesional'), ('laboral', 'Laboral')], default='profesional', max_length=50),
        ),
        migrations.AlterField(
            model_name='anunciopractica',
            name='modalidad',
            field=models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('híbrido', 'Híbrido')], default='presencial', max_length=50),
        ),
    ]
