# Generated by Django 5.2.6 on 2025-10-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_anunciopractica_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpostulante',
            name='cv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
