# Generated by Django 5.2.6 on 2025-10-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_perfilpostulante_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'empresa'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('empresa', 'Empresa'), ('capacitador', 'Capacitador')], default='alumno', max_length=20),
        ),
    ]
