# Generated by Django 5.2.6 on 2025-10-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_customuser_company_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciopractica',
            name='cantidad_horas',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de horas de la práctica'),
        ),
        migrations.AlterField(
            model_name='anunciopractica',
            name='duracion_meses',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='anunciopractica',
            name='tipo_practica',
            field=models.CharField(choices=[('Profesional', 'Profesional'), ('Laboral', 'Laboral')], default='Profesional', max_length=50),
        ),
    ]
