# Generated by Django 5.2.6 on 2025-10-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_anunciopractica_cantidad_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpostulante',
            name='institucion',
            field=models.CharField(blank=True, choices=[('DUOC UC', 'DUOC UC'), ('INACAP', 'INACAP'), ('Universidad de Chile', 'Universidad de Chile'), ('Pontificia Universidad Católica de Chile', 'Pontificia Universidad Católica de Chile'), ('Universidad Técnica Federico Santa María', 'Universidad Técnica Federico Santa María'), ('Universidad de Santiago de Chile', 'Universidad de Santiago de Chile'), ('Universidad de Concepción', 'Universidad de Concepción'), ('Universidad Adolfo Ibáñez', 'Universidad Adolfo Ibáñez'), ('Universidad Austral de Chile', 'Universidad Austral de Chile'), ('Universidad Diego Portales', 'Universidad Diego Portales')], help_text='Casa de estudios del postulante', max_length=100, null=True),
        ),
    ]
