# Generated by Django 5.2.6 on 2025-10-21 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_perfilpostulante_institucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacapacitacion',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa que agenda la capacitación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_capacitacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
