# Generated by Django 5.2.6 on 2025-10-30 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_fichacapacitacion_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacapacitacion',
            name='postulacion',
            field=models.ForeignKey(blank=True, help_text='Postulación específica a la que pertenece esta capacitación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to='portal.postulacion'),
        ),
    ]
