# Generated by Django 5.2.6 on 2025-10-30 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_fichacapacitacion_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(choices=[('creada', 'Creada'), ('estado_cambiado', 'Estado cambiado')], max_length=50)),
                ('old_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('new_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.anunciopractica')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulacion_logs', to=settings.AUTH_USER_MODEL)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='portal.postulacion')),
                ('postulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.perfilpostulante')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
