# Generated by Django 5.2.8 on 2025-11-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_postulacionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Determina si la cuenta puede acceder al sistema. Empresas y capacitadores requieren verificación por admin.'),
        ),
        migrations.AddField(
            model_name='fichacapacitacion',
            name='detalle',
            field=models.TextField(blank=True, help_text='Detalles adicionales: horario, contacto, ubicación, etc. (máx. 250 caracteres)', max_length=250, null=True),
        ),
    ]
