services:
  - type: web
    name: capstone
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn capstone.wsgi:application"
    envVars:
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false   # ⚠️ aquí la defines manualmente en el dashboard de Render
      - key: DB_HOST
        value: db.udkjkpjpvurcegbpkyjk.supabase.co
      - key: DB_PORT
        value: 5432
      - key: PYTHON_VERSION
        value: 3.13.4
